scrape_configs:
  - job_name: 'Realtime Monitor'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'Temperature Groups'

